<?php

/**
 * Handles Radiant pay payments
 *
 * @package    Payments
 * @author     
 * @copyright  
 * @license    http://www.php.net/license/3_01.txt  PHP License 3.01
 * @version    
 * @link       
 */
App::uses('PaymentAppController', 'Payments.Controller');

class B2cryptoController extends PaymentAppController {

    /**
     * Controller name
     * @var $name string
     */
    public $name = 'B2crypto';
    public $slug = 'b2crypto';

    /**
     * Models
     * @var array
     */
    public $uses = array('Payments.B2crypto', 'User', 'Payment', 'Deposit', 'Alert');

    const DEBUG_MODE = true;

    public function beforeFilter() {
        $this->Auth->allow('deposit', 'success', 'failed', 'status', 'pingStatus');
        parent::beforeFilter();
    }

    public function deposit($amount) {
        $this->layout = 'payment';

        try {
            $user_id = CakeSession::read('Auth.User.id');

            if (!$user_id)
                throw new Exception(__("Please login first."));
            $user = $this->User->getUser($user_id);
            $user['User']['deposit_IP'] = isset($_SERVER['HTTP_X_FORWARDED_FOR']) ? $_SERVER['HTTP_X_FORWARDED_FOR'] : $this->request->clientIp();

            $transaction_data = array(
                'type' => PaymentAppController::PAYMENT_TYPE_DEPOSIT,
                'user' => $user,
                'amount' => number_format($amount, 2, '.', ''),
            );

            $transaction = $this->B2crypto->prepareTransaction($transaction_data);
            $this->Payment->createPayment($transaction_data['user']['User']['id'], $this->name, null, $transaction['B2crypto']['id'], $transaction_data['amount'], $transaction_data['user']['Currency']['name'], __(array_search(PaymentAppModel::TRANSACTION_PENDING, PaymentAppModel::$humanizeStatuses)), PaymentAppModel::PAYMENT_TYPE_DEPOSIT);

            $transaction_data['Transaction'] = $transaction;
            $url = $this->B2crypto->config['Config']['PAYMENT_URL'] . '/payments';
            $data = $this->B2crypto->setRequestData($transaction_data);
            $header = array(
                'Content-Type: application/json',
                'Authorization: Basic ' . base64_encode($this->B2crypto->config['Config']['MERCHANT_ID'] . ':' . $this->B2crypto->config['Config']['SECRET_KEY'])
            );

            $request = json_decode($this->B2crypto->cURLPost($url, $header, json_encode($data)));
            $request->transaction_id = $transaction['B2crypto']['id'];

            if ($request->id) {
                $transaction['B2crypto']['remote_id'] = $request->id;
                $this->B2crypto->save($transaction);
                $this->set('checkoutUrl', $request->checkoutUrl);
            } else {
                $this->B2crypto->setStatus($request);
            }
            //check this, may need to be put in shell
            //$response = $this->B2crypto->getStatus($request);
        } catch (Exception $ex) {
            $user_id = CakeSession::read('Auth.User.id');
            $this->Alert->createAlert($user_id, "Deposit", 'B2crypto Error:' . $ex->getMessage(), $this->__getSqlDate());
            echo 'Error: ', $ex->getMessage();
        }
    }

    /*
     * Return URL: "http://82.214.112.218/payments/b2crypto/status/#requestId#";
     * requestId - generated by merchant-us
     */

    public function status($transaction_id) {
        $this->autoRender = false;
//TO CHECK
        if (self::DEBUG_MODE) {
            $this->log('STATUS RESPONSE', 'B2crypto.Deposit');
            $this->log($this->request, 'B2crypto.Deposit');
        }

        $response = $this->request->data;
        $transaction_id = $response->requestId;



        if ($transaction_id) {
            $response = $this->B2crypto->setStatus($transaction_id);
         
            $this->parseStatus($response, $transaction_id);
        }
    }


    private function parseStatus($response, $transaction_id) {

        $transaction = $this->B2crypto->getItem($response['transaction_id']);

        if (($response['success'] == true) && ($response['continue'] == false)) {//success
            $this->redirect(array('action' => 'success', $transaction['B2crypto']['id']));
        } elseif (($response['success'] == true) && ($response['continue'] == true)) {
            //pending
        } elseif (($response['success'] == false) && ($response['continue'] == false)) {//failed
            $this->redirect(array('action' => 'failed', $transaction['B2crypto']['id']));
        } else {
            $this->Alert->createAlert($transaction['B2crypto']['user_id'], "Deposit", 'B2crypto: Failed transaction. Transaction ID: ' . $transaction['B2crypto']['id'], $this->__getSqlDate());
            $this->redirect(array('action' => 'failed', $transaction['B2crypto']['id']));
        }
    }
    
    
    public function pingStatus() {
        $this->autoRender = false;
        $this->B2crypto->resolveStatus();
    }

    public function success($transaction_id) {
        $this->layout = 'payment';
        $transaction = $this->B2crypto->getItem($transaction_id);
        $user = $this->User->getItem($transaction['B2crypto']['user_id']);
        $currency = $this->Currency->getById($user['User']['currency_id']);

        $vars = array(
            'site_title' => Configure::read('Settings.defaultTitle'),
            'site_name' => Configure::read('Settings.websiteTitle'),
            'first_name' => $user['User']['first_name'],
            'last_name' => $user['User']['last_name'],
            'deposit_amount' => $transaction['B2crypto']['amount'],
            'deposit_currency' => $currency,
            'deposit_method' => 'B2crypto' . ' ' . $transaction['B2crypto']['code'],
        );
        $this->__sendMail('deposit', $user['User']['email'], $vars);
        $this->set('transaction', $transaction);
    }

    public function failed($transaction_id) {
        $this->layout = 'payment';
        $this->set('transaction', $this->B2crypto->getItem($transaction_id));
    }

    public function admin_index($status) {
        $this->layout = 'admin';

        // Draw charts START
        $statusesChart = array(
            __('Completed') => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_COMPLETED)),
            __('Pending') => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_PENDING)),
            __('Canceled') => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_REJECTED))
        );

        $amountChart = array(
            '1-50' . Configure::read('Settings.currency') => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_COMPLETED, 'B2crypto.amount BETWEEN ? AND ?' => array(1, 50))),
            '50-150' . Configure::read('Settings.currency') => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_COMPLETED, 'B2crypto.amount BETWEEN ? AND ?' => array(50, 150))),
            '150-500' . Configure::read('Settings.currency') => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_COMPLETED, 'B2crypto.amount BETWEEN ? AND ?' => array(150, 500))),
            '500-1000' . Configure::read('Settings.currency') => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_COMPLETED, 'B2crypto.amount BETWEEN ? AND ?' => array(500, 1000))),
            '1000' . Configure::read('Settings.currency') . ' >' => $this->B2crypto->getCount(array('B2crypto.status' => B2crypto::TRANSACTION_COMPLETED, 'B2crypto.amount >= ?' => array(1000)))
        );
        $this->set('chartsData', array(__('Statuses chart') => $statusesChart, __('Amount chart') => $amountChart));
        // Draw charts END

        if (!empty($this->request->data)) {

            $this->Session->write('B2crypto.SearchValues', $this->request->data);

            $this->set('search_values', $this->request->data);
            $this->set('tabs', null);

            foreach ($this->request->data['B2crypto'] as $key => $search_fields) {

                if (empty($search_fields))
                    continue;
                //search between dates
                if ($key == 'date_from') {
                    $conditions[] = array('B2crypto.date >=' => date("Y-m-d H:i:s", strtotime($search_fields)));
                    continue;
                }
                if ($key == 'date_to') {
                    $conditions[] = array('B2crypto.date <=' => date("Y-m-d H:i:s", strtotime($search_fields)));
                    continue;
                }
                //search between amounts
                if ($key == 'amount_from') {
                    $conditions[] = array('B2crypto.amount >=' => $search_fields);
                    continue;
                }
                if ($key == 'amount_to') {
                    $conditions[] = array('B2crypto.amount <=' => $search_fields);
                    continue;
                }
                if ($key == 'unique') {
                    if ($search_fields == 1)
                        $group = 'User.id';
                    continue;
                }
                if ($search_fields != "")
                    $conditions['B2crypto.' . $key] = $search_fields;
            }
            $this->Session->write('B2crypto.SearchConditions', $conditions);
        } else if ($this->request->query['dashboard']) {
            switch ($this->request->query['dashboard']) {
                // switch case for daily payments
                case 1:
                    $conditions = array(
                        'B2crypto.status' => B2crypto::TRANSACTION_COMPLETED,
                        'B2crypto.date >' => date('Y-m-d 00:00:00'),
                        'B2crypto.date <=' => date('Y-m-d 23:59:59')
                    );
                    $this->set('tabs', null);
                    break;
                // switch case for monthly payments
                case 2:
                    $conditions = array(
                        'B2crypto.status' => B2crypto::TRANSACTION_COMPLETED,
                        'B2crypto.date >' => date("Y-m-d 00:00:00", strtotime('first day of this month')),
                        'B2crypto.date <=' => date("Y-m-d H:i:s", strtotime('now'))
                    );
                    $this->set('tabs', null);
                    break;
            }
        } else {
            //if (empty($this->request->params['named'])) $this->Session->write('B2crypto.SearchConditions', "");
            //if (empty($this->request->params['named'])) $this->Session->write('B2crypto.SearchValues', "");
            $conditions = $this->Session->read('B2crypto.SearchConditions');
            $this->set('search_values', $this->Session->read('B2crypto.SearchValues'));
            //if conditions not exists
            if (empty($conditions)) {
                $this->set('tabs', $this->B2crypto->getTabs($this->request->params));

                if (in_array($status, B2crypto::$orderStatuses)) {
                    $conditions['B2crypto.status'] = $status;
                } else {
                    //$conditions['B2crypto.status'] = B2crypto::TRANSACTION_PENDING;
                }
            }
        }

        $this->paginate['group'] = $group;
        $this->paginate['conditions'] = $conditions;
        $this->paginate['order'] = array('B2crypto.id' => 'DESC');

        $this->paginate['contain'] = array('User');

        $data = $this->paginate($this->B2crypto->name, array(), array('username', 'amount', 'B2crypto.id', 'date'));

        foreach ($data as &$row) {
            $row['User']['Currency'] = $this->Currency->getItem($row['User']['currency_id'])['Currency'];
        }

        //no need of tabs
        $this->set('tabs', null);
        $this->set('HumanStatus', B2crypto::$humanizeStatuses);
        $this->set('data', $data);
        $this->set('search_fields', $this->B2crypto->getSearch($this->name));
    }

}
